# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [17]:
# Exercise 1
import numpy as np
arra=np.arange(1,11)
print(arra)



[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [20]:
# Exercise 2
import numpy as np
matrix=np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [16]:
# Exercise 3
import numpy as np 
num_1=np.linspace(0,5,10)
print(num_1)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


# Exercise 4

In [29]:
#  Create a 5x5 identity matrix using NumPy.# Exercise
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [32]:
# Exercise 5
random_1=np.random.rand(4,4)
print(random_1)

[[0.57282564 0.8425614  0.79228986 0.4438535 ]
 [0.49282707 0.37465485 0.60200846 0.19867406]
 [0.509927   0.09173576 0.15046728 0.54950655]
 [0.46971381 0.47856628 0.17406286 0.52598802]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [28]:
# Exercise 6
a=np.array([[1,1,2],[2,2,3]])
print(a.shape)

(2, 3)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [3]:
# Exercise 7
import numpy as np

arr_1d = np.arange(1, 17)  
arr_4x4 = np.reshape(arr_1d, (4, 4))
print(arr_4x4)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [7]:
# Exercise 8
data_1=np.array([[1,1,2],[2,2,3]])
print(data_1.dtype)

int32



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [13]:
# Exercise 9
arr=np.arange(1,101)
even_num=arr[arr%2==0]
print(even_num)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [20]:
# Exercise 10
matrix = np.random.randint(10, 50, size=(6, 6))
print(matrix)

[[23 49 49 38 23 22]
 [44 47 10 38 19 46]
 [39 30 42 40 10 43]
 [48 28 17 30 22 49]
 [32 40 15 23 38 22]
 [21 31 41 25 42 31]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [25]:
# Exercise 11
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

submatrix = a[1:3, 1:3]
print(submatrix)



[[ 6  7]
 [10 11]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [29]:
# Exercise 12
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
total_sum = arr.sum()
print(total_sum)

45



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [31]:
# Exercise 13

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate mean
mean_val = np.mean(arr)

# Calculate median
median_val = np.median(arr)

# Calculate standard deviation
std_dev = np.std(arr)

print( mean_val)
print( median_val)
print( std_dev)


5.5
5.5
2.8722813232690143



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [33]:
# Exercise 14
arr = np.array([10, 25, 7, 42, 18, 3])

max_val = np.max(arr)
min_val = np.min(arr)

print( max_val)
print( min_val)

42
3



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [35]:
# Exercise 15
arr = np.random.randint(0, 100, size=20)


max_index = np.argmax(arr)

print( arr)
print( max_index)
print( arr[max_index])

[ 2 65 10 31 84 26 40 37 37 60 37 47 95 97  8 98  1 49 97 38]
15
98



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [38]:
# Exercise 16
arr = np.array([1, 2, 3, 4, 5])


reversed_arr = arr[::-1]

print( arr)
print( reversed_arr)


[1 2 3 4 5]
[5 4 3 2 1]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [44]:
# Exercise 17
A = np.array([[1, 2, 3],
              [4, 1, 2],
              [3, 2, 0]])

B = np.array([[0, 1, 2],
              [2, 5, 1],
              [2, 2, 1]])


result = A * B

print( A)
print( B)
print( result)

[[1 2 3]
 [4 1 2]
 [3 2 0]]
[[0 1 2]
 [2 5 1]
 [2 2 1]]
[[0 2 6]
 [8 5 2]
 [6 4 0]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [48]:
# Exercise 18
arr = np.array([2, 4, 6])
diag_matrix = np.diag(arr)

print( arr)
print(diag_matrix)

[2 4 6]
[[2 0 0]
 [0 4 0]
 [0 0 6]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [64]:
# Exercise 19
A = np.array([[2, 4],
              [1, 3]])

B = np.array([[5, 6],
              [7, 8]])


result = A @ B
print(result)

[[38 44]
 [26 30]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [59]:
# Exercise 20
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
arr_1d = arr_2d.flatten()
print( arr_2d)
print( arr_1d)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [62]:
# Exercise 21
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))

print( a)
print( b)
print(result)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:

---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [70]:
# Exercise 22
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print( a)
print( b)
print( result)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [72]:
# Exercise 23
arr = np.array([10, 20, 30, 40, 50, 60])

sub_arrays = np.split(arr, 3)

for i, sub in enumerate(sub_arrays):
    print(f"Sub-array {i+1}: {sub}")

Sub-array 1: [10 20]
Sub-array 2: [30 40]
Sub-array 3: [50 60]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [80]:
# Exercise 24
arr = np.random.rand(3, 3)
rounded_arr = np.round(arr, 2)

print( arr)
print( rounded_arr)

[[0.03725226 0.23571443 0.92082472]
 [0.80911177 0.52463779 0.75848728]
 [0.3848102  0.48818805 0.8584211 ]]
[[0.04 0.24 0.92]
 [0.81 0.52 0.76]
 [0.38 0.49 0.86]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [82]:
# Exercise 25
arr = np.array([1, 2, 2, 3, 4, 4, 5, 1, 6])
unique_elements = np.unique(arr)

print( arr)
print( unique_elements)


[1 2 2 3 4 4 5 1 6]
[1 2 3 4 5 6]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [84]:
# Exercise 26
arr = np.array([2, 7, 1, 9, 4, 6])
arr[arr < 5] = 5
print(arr)

[5 7 5 9 5 6]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [86]:
# Exercise 27
arr = np.array([1, 2, 3, 4, 5])
cumsum_arr = np.cumsum(arr)
print( arr)
print(cumsum_arr)

[1 2 3 4 5]
[ 1  3  6 10 15]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [88]:
# Exercise 28
arr = np.array([0, 3, 0, 4, 5, 0, 6])
non_zero_count = np.count_nonzero(arr)
print( arr)
print( non_zero_count)

[0 3 0 4 5 0 6]
4



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [92]:
# Exercise 29
arr = np.random.randint(1, 101, size=10)
print( arr)
sorted_arr = np.sort(arr)
print(sorted_arr)

[34  8 55 46  7 23 62 17 42 98]
[ 7  8 17 23 34 42 46 55 62 98]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [94]:
# Exercise 30
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_sum = np.sum(matrix, axis=1)
col_sum = np.sum(matrix, axis=0)

print(matrix)
print( row_sum)
print( col_sum)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]
[12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [96]:
# Exercise 31
arr = np.random.randint(10, 100, size=(3, 3))
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())

print( arr)
print( normalized_arr)

[[51 40 88]
 [91 88 33]
 [42 83 48]]
[[0.31034483 0.12068966 0.94827586]
 [1.         0.94827586 0.        ]
 [0.15517241 0.86206897 0.25862069]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [98]:
# Exercise 32
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print( a)
print( b)
print( dot_product)

[1 2 3]
[4 5 6]
32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [100]:
# Exercise 33
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
trace = np.trace(matrix)
print (matrix)
print( trace)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15



---

### Exercise 34:
Create a 2D array and swap two rows.


In [102]:
# Exercise 34
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)
arr[[0, 2]] = arr[[2, 0]]
print( arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [104]:
# Exercise 35
arr = np.array([1, 2, 3, 4, 5])
column_vector = arr.reshape(-1, 1)

print( arr)
print( column_vector)

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [106]:
# Exercise 36
matrix = np.array([[2, 5, 3],
                   [1, -2, -1],
                   [1, 3, 4]])
determinant = np.linalg.det(matrix)
print(matrix)
print(determinant)


[[ 2  5  3]
 [ 1 -2 -1]
 [ 1  3  4]]
-20.000000000000007



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [109]:
# Exercise 37
A = np.array([[4, 2],
              [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print( A)
print( eigenvalues)
print( eigenvectors)


[[4 2]
 [1 3]]
[5. 2.]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [115]:
# Exercise 38
A = np.array([[2, 3],
              [5, 4]])
b = np.array([8, 13])
x = np.linalg.solve(A, b)
print( x[0])
print( x[1])

1.0
2.0



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [117]:
# Exercise 39
arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr)

[1. 2. 3. 4. 5.]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [119]:
# Exercise 40
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
diagonal_elements = np.diag(matrix)
print(matrix)
print( diagonal_elements)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [121]:
# Exercise 41
arr = np.random.uniform(0, 100, 100)
clipped_arr = np.clip(arr, 10, 50)
print( arr[:10])      
print( clipped_arr[:10]) 

[18.84879496 16.61413735 23.04662984 53.66442482 54.54774887 43.18039629
  1.42288568 60.28369929 76.61624162 29.46753157]
[18.84879496 16.61413735 23.04662984 50.         50.         43.18039629
 10.         50.         50.         29.46753157]



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [125]:
# Exercise 42
arr = np.array([[4, -3, 2],
                [-1, 5, -6],
                [7, -8, 9]])
print(arr)
arr[arr < 0] = 0
print(arr)

[[ 4 -3  2]
 [-1  5 -6]
 [ 7 -8  9]]
[[4 0 2]
 [0 5 0]
 [7 0 9]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [127]:
# Exercise 43
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
inner_product = np.inner(a, b)
outer_product = np.outer(a, b)
print( a)
print( b)
print( inner_product)
print( outer_product)


[1 2 3]
[4 5 6]
32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [137]:
# Exercise 44
points = np.array([[1, 2],
                   [4, 6],
                   [7, 8],
                   [2, 1]])
diffs = points[:, np.newaxis, :] - points[np.newaxis, :, :]  
distances = np.sqrt(np.sum(diffs**2, axis=-1))
print( distances)

Pairwise distances:
 [[0.         5.         8.48528137 1.41421356]
 [5.         0.         3.60555128 5.38516481]
 [8.48528137 3.60555128 0.         8.60232527]
 [1.41421356 5.38516481 8.60232527 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [42]:
# Exercise 45
dtype = [('name', 'U10'), ('age', 'i4'), ('height', 'f4')]
data = np.array([
    ('Alice', 25, 5.5),
    ('Bob', 30, 6.1),
    ('Charlie', 22, 5.8)
], dtype=dtype)
print(data)
print(data['name'])
print(data['age'])
print(data['height'])


[('Alice', 25, 5.5) ('Bob', 30, 6.1) ('Charlie', 22, 5.8)]
['Alice' 'Bob' 'Charlie']
[25 30 22]
[5.5 6.1 5.8]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [145]:
# Exercise 46
matrix = np.random.randint(0, 10, size=(5, 5))
unique_values, counts = np.unique(matrix, return_counts=True)

print("Matrix:\n", matrix)
print("\nValue counts:")
for val, count in zip(unique_values, counts):
    print(f"{val}: {count}")

Matrix:
 [[6 0 0 7 8]
 [4 5 1 5 5]
 [3 1 4 2 7]
 [3 7 6 1 2]
 [2 7 4 6 8]]

Value counts:
0: 2
1: 3
2: 3
3: 2
4: 3
5: 3
6: 3
7: 4
8: 2



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [147]:
# Exercise 47
arr = np.random.rand(3, 3)
row_means = arr.mean(axis=1).reshape(3, 1)
result = arr - row_means
print( arr)
print( row_means)
print( result)

[[0.39964259 0.53360978 0.99645742]
 [0.10575797 0.0269279  0.79084423]
 [0.33185871 0.06561163 0.56725026]]
[[0.64323659]
 [0.30784337]
 [0.32157353]]
[[-0.24359401 -0.10962682  0.35322083]
 [-0.2020854  -0.28091546  0.48300086]
 [ 0.01028518 -0.25596191  0.24567673]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [149]:
# Exercise 48
arr = np.random.randint(0, 101, size=20)
any_greater_than_50 = np.any(arr > 50)
print( arr)
print( any_greater_than_50)

[69 58 86 33 21 82 79 59 94 90 97 10 39 56 23 71 50 30 88 57]
True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [151]:
# Exercise 49
arr = np.array([10, 20, 30, 40, 50, 60, 70])
window_size = 3
moving_avg = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')

print(arr)
print(moving_avg)

[10 20 30 40 50 60 70]
[20. 30. 40. 50. 60.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [153]:
# Exercise 50
x = np.array([10, 20, 30, 40, 50])
y = np.array([5, 15, 25, 35, 45])
corr_matrix = np.corrcoef(x, y)
pearson_corr = corr_matrix[0, 1]

print(corr_matrix)
print(pearson_corr)

[[1. 1.]
 [1. 1.]]
1.0



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [155]:
# Exercise 51
radians = np.array([0, np.pi/6, np.pi/4, np.pi/2, np.pi])
degrees = np.degrees(radians)
print( radians)
print(degrees)

[0.         0.52359878 0.78539816 1.57079633 3.14159265]
[  0.  30.  45.  90. 180.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [157]:
# Exercise 52
arr = np.random.randint(0, 101, size=10)
variance = np.var(arr)
std_deviation = np.std(arr)
print(arr)
print(variance)
print(std_deviation)

[27 41 65 63  1  0 21  3 53 16]
571.0
23.895606290697042



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [159]:
# Exercise 53
arr = np.array([[10, 25, 8],
                [35, 12, 50],
                [5, 40, 30]])
max_indices_row = np.argmax(arr, axis=1)  
max_indices_col = np.argmax(arr, axis=0)  
print(arr)

[[10 25  8]
 [35 12 50]
 [ 5 40 30]]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [44]:
# Exercise 54
A = np.array([[4, 7],
              [2, 6]])
A_inv = np.linalg.inv(A)
print( A)
print( A_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [51]:
# Exercise 55
arr = np.random.rand(10)  
mean = np.mean(arr)
std = np.std(arr)
standardized_arr = (arr - mean) / std
print(arr)
print(standardized_arr)

[0.66521551 0.96680612 0.62537991 0.42607036 0.00841928 0.4688118
 0.90638429 0.32192892 0.07584201 0.53128998]
[ 0.55610818  1.56888782  0.42233519 -0.24697166 -1.64949709 -0.10344046
  1.36598364 -0.59669186 -1.42308299  0.10636923]



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [53]:
# Exercise 56
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
addition = a + b
subtraction = a - b

print(a)
print( b)
print( addition)
print(subtraction)


[1 2 3 4 5]
[5 4 3 2 1]
[6 6 6 6 6]
[-4 -2  0  2  4]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [11]:
# Exercise 57
import numpy as np
arr=np.random.rand(10)
max_index=np.argmax(arr)
print(max_index)

6



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [13]:
# Exercise 58
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
rotated_arr = np.rot90(arr)
print(arr)
print(rotated_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 6 9]
 [2 5 8]
 [1 4 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [15]:
# Exercise 59
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
fro_norm = np.linalg.norm(A, 'fro')
print(A)
print(fro_norm)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
16.881943016134134



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [17]:
# Exercise 60
arr = np.arange(3*4*5).reshape(3, 4, 5)
print( arr)
subarray = arr[0:2, 1:3, 1:4]
print(subarray)
print(subarray.shape)



Original 3D array:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
[[[ 6  7  8]
  [11 12 13]]

 [[26 27 28]
  [31 32 33]]]
(2, 2, 3)



---